force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Amount_of_line_items__c.field-meta.xml
<CustomField>
    <fullName>Amount_of_line_items__c</fullName>
    <label>Amount of line items</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <label>Invoice Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/InvoiceLineItemTriggerHandler.cls
public with sharing class InvoiceLineItemTriggerHandler {
  public static Boolean enablesTrigger = true;

  public static void handleAfterInsert(List<Invoice_Line_Item__c> invoiceLineItems) {
    if (invoiceLineItems != null && !invoiceLineItems.isEmpty()) {
      updateInvoiceField(invoiceLineItems);
    }
  }

  public static void handleAfterDelete(List<Invoice_Line_Item__c> invoiceLineItems) {
    if (invoiceLineItems != null && !invoiceLineItems.isEmpty()) {
      updateInvoiceField(invoiceLineItems);
    }
  }

  private static void updateInvoiceField(List<Invoice_Line_Item__c> invoiceLineItems) {
    Set<Id> invoiceIds = new Set<Id>();
    for (Invoice_Line_Item__c invoiceLineItem : invoiceLineItems) {
      invoiceIds.add(invoiceLineItem.Invoice__c);
    }

    List<Invoice__c> invoices = InvoiceLineItemTriggerManager.getInvoiceByIds(invoiceIds);
    if (invoices != null && !invoices.isEmpty()) {
      for (Invoice__c invoice : invoices) {
        invoice.Amount_of_line_items__c = invoice.Invoice_Line_Items__r.size();
      }
      update invoices;
    }
  }
}